import { Document, Paragraph, TextRun, HeadingLevel, Packer, AlignmentType, Header, Footer, PageNumber, convertInchesToTwip } from 'docx';

export const config = { api: { bodyParser: { sizeLimit: '2mb' } } };

function parseDoc(text) {
  const lines = text.split('\n');
  const children = [];
  for (const line of lines) {
    const t = line.trim();
    if (!t) { children.push(new Paragraph({ spacing: { after: 80 } })); continue; }
    if (t.match(/^# /) || (t === t.toUpperCase() && t.length > 4 && t.length < 80 && !t.match(/^\d/))) {
      children.push(new Paragraph({ text: t.replace(/^# /, ''), heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 160 } })); continue;
    }
    if (t.match(/^## /)) { children.push(new Paragraph({ text: t.replace(/^## /, ''), heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 120 } })); continue; }
    if (t.match(/^[-•*] /)) {
      children.push(new Paragraph({ children: [new TextRun({ text: t.replace(/^[-•*] /, ''), size: 24, font: 'Times New Roman' })], bullet: { level: 0 }, spacing: { after: 80 } })); continue;
    }
    if (t.match(/^\d+\.\d+/) || t.match(/^\d+\.\s+[A-Z]/)) {
      children.push(new Paragraph({ children: [new TextRun({ text: t, bold: t.match(/^\d+\.\s+[A-Z]/), size: 24, font: 'Times New Roman' })], indent: { left: t.match(/^\d+\.\d+/) ? convertInchesToTwip(0.25) : 0 }, spacing: { after: 100 }, alignment: AlignmentType.JUSTIFIED })); continue;
    }
    const parts = t.split(/(\*\*[^*]+\*\*)/);
    const runs = parts.map(p => p.startsWith('**') && p.endsWith('**')
      ? new TextRun({ text: p.slice(2, -2), bold: true, size: 24, font: 'Times New Roman' })
      : new TextRun({ text: p, size: 24, font: 'Times New Roman' })
    );
    children.push(new Paragraph({ children: runs, spacing: { after: 120 }, alignment: AlignmentType.JUSTIFIED }));
  }
  return children;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  const { text, fileName, documentType } = req.body;
  if (!text) return res.status(400).json({ error: 'Document text required' });

  try {
    const cleanName = (fileName || 'document').replace(/\.[^/.]+$/, '');
    const doc = new Document({
      styles: {
        default: { document: { run: { font: 'Times New Roman', size: 24 } } },
        paragraphStyles: [
          { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', run: { font: 'Times New Roman', size: 32, bold: true, color: '1a2a4a' }, paragraph: { spacing: { before: 400, after: 200 } } },
          { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', run: { font: 'Times New Roman', size: 28, bold: true, color: '1a2a4a' }, paragraph: { spacing: { before: 320, after: 160 } } },
        ],
      },
      sections: [{
        properties: { page: { margin: { top: convertInchesToTwip(1.25), right: convertInchesToTwip(1.25), bottom: convertInchesToTwip(1.25), left: convertInchesToTwip(1.25) } } },
        headers: { default: new Header({ children: [new Paragraph({ children: [new TextRun({ text: `${documentType || 'Legal Document'} — Revised | CONFIDENTIAL`, size: 18, color: '666666', font: 'Times New Roman' })], alignment: AlignmentType.RIGHT })] }) },
        footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun({ text: 'Generated by LexAI  |  Page ', size: 18, color: '888888', font: 'Times New Roman' }), new TextRun({ children: [PageNumber.CURRENT], size: 18, color: '888888', font: 'Times New Roman' }), new TextRun({ text: ' of ', size: 18, color: '888888', font: 'Times New Roman' }), new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: '888888', font: 'Times New Roman' })], alignment: AlignmentType.CENTER })] }) },
        children: parseDoc(text),
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${cleanName}-revised.docx"`);
    res.setHeader('Content-Length', buffer.length);
    res.send(buffer);
  } catch (err) {
    console.error('[DOCX Error]', err);
    res.status(500).json({ error: err.message || 'DOCX generation failed' });
  }
}
